---
# ------------------- Deployment ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdns-repeater
  labels:
    app: mdns-repeater
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mdns-repeater
  template:
    metadata:
      labels:
        app: mdns-repeater
    spec:
      hostNetwork: true
      containers:
      - name: mdns-repeater
        image: angelnu/mdns-repeater:latest
        env:
        # - name: hostNIC
        #   value: eth0
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: dockerNIC
          value: weave
        # Verbose mode
        # - name: options
        #   value: -v
